# API de prueba

### Rutas de Autenticación

# POST /api/auth/login
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email": "admin@example.com",
    "password": "admin123"
}

### Rutas de Test

# POST /api/health
GET http://localhost:3000/api/health
